---
- hosts: localhost
  connection: local
  gather_facts: no

#  vars:
#    ansible_python_interpreter: '{{ ansible_playbook_python }}'
#    ansible_python_interpreter: /Users/pgriffit/ansible-navigator_demo/venv/bin/python

  tasks:

#    - pip:
#        name: openshift

    - name: Create a k8s namespace
      k8s:
        kubeconfig: /etc/ansible/files/kubeconfig
        context: preprod-dev
        name: testing
        api_version: v1
        kind: Namespace
        state: present
