apiVersion: extensions/v1beta1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-scaler 
spec:
  scaleRef:
    kind: DeploymentConfig 
    name: blue
    apiVersion: v1 
    subresource: scale
  minReplicas: 2 
  maxReplicas: 5 
  cpuUtilization:
    targetPercentage: 5
